# Generated by Django 5.2.2 on 2025-06-08 15:03

import list.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistuser',
            name='referral_code',
            field=models.CharField(default=list.models.generate_unique_referral_code, max_length=10, unique=True),
        ),
    ]
